function(add_src_exe)
    set(_options)
    set(_one_arg)
    set(_multi_arg SOURCE LINK_LIBS)
    cmake_parse_arguments(_prefix "${_options}" "${_one_arg}" "${_multi_arg}"
                          ${ARGN})
    set(_unuse_list ${_prefix_UNPARSED_ARGUMENTS})
    set(_source ${_prefix_SOURCE})
    set(_link_libs ${_prefix_LINK_LIBS})

    foreach(t ${_link_libs})
        get_target_property(target_type ${t} TYPE)
        # message("target ${t} type is ${target_type}")
        if(target_type STREQUAL "SHARED_LIBRARY")
            install(TARGETS ${t} COMPONENT runtime)
        endif()
    endforeach()

    set(libraries_name ${_link_libs})
    if(EXISTS ${CMAKE_CURRENT_LIST_DIR}/main.cpp)
        message(".... application name: ${PROJECT_NAME}")
        add_executable(${PROJECT_NAME} main.cpp ${_source})

        target_link_libraries(${PROJECT_NAME} PRIVATEATE ${libraries_name})
        install(TARGETS ${PROJECT_NAME} COMPONENT runtime)
    endif()
    if(EXISTS ${CMAKE_CURRENT_LIST_DIR}/bin)
        file(GLOB_RECURSE bin_files "bin/*.cpp")
        foreach(f ${bin_files})
            message(".... application name: bin/${name}")
            get_filename_component(name ${f} NAME_WE)
            add_executable(${name} ${f})

            target_link_libraries(${name} PRIVATE ${libraries_name})
            install(TARGETS ${name} COMPONENT runtime)
        endforeach()
    endif()
endfunction()
