function(add_src_exe)
    set(_options)
    set(_one_arg)
    set(_multi_arg SOURCE LINK_LIBS)
    cmake_parse_arguments(_prefix "${_options}" "${_one_arg}" "${_multi_arg}"
                          ${ARGN})
    set(_unuse_list ${_prefix_UNPARSED_ARGUMENTS})
    set(_source ${_prefix_SOURCE})
    set(_link_libs ${_prefix_LINK_LIBS})

    set(libraries_name ${_link_libs})
    if(EXISTS main.cpp)
        add_executable(${PROJECT_NAME} main.cpp ${_source})

        target_link_libraries(${PROJECT_NAME} PRIVATE ${libraries_name})
        install(TARGETS ${PROJECT_NAME})
    endif()
    if(EXISTS bin)
        file(GLOB_RECURSE bin_files "bin/*.cpp")
        foreach(f ${bin_files})
            get_filename_component(name ${f} NAME_WE)
            add_executable(${name} ${f})

            target_link_libraries(${name} PRIVATE ${libraries_name})
            install(TARGETS ${name})
        endforeach()
    endif()
endfunction()
