include(${CMAKE_CURRENT_LIST_DIR}/check_clang_tidy.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/check_memory.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/check_profile.cmake)

if(NOT TARGET checker)
    add_custom_target(checker)
endif()
if(TARGET ${clang_tidy_target})
    add_dependencies(checker ${clang_tidy_target})
endif()
if(TARGET ${check_memory_target})
    add_dependencies(checker ${check_memory_target})
endif()
if(TARGET ${check_profile_target})
    add_dependencies(checker ${check_profile_target})
endif()

if(NOT TARGET unchecker)
    add_custom_target(unchecker)
endif()
if(TARGET ${clang_tidy_cancel_target})
    add_dependencies(unchecker ${clang_tidy_cancel_target})
endif()
if(TARGET ${check_memory_cancel_target})
    add_dependencies(unchecker ${check_memory_cancel_target})
endif()
if(TARGET ${check_profile_cancel_target})
    add_dependencies(unchecker ${check_profile_cancel_target})
endif()
