include(${CMAKE_CURRENT_LIST_DIR}/check_clang_tidy.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/check_memory.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/check_profile.cmake)

if (NOT TARGET checker)
    add_custom_target(checker)
endif()
add_dependencies(checker ${clang_tidy_target})
add_dependencies(checker ${check_memory_target})
add_dependencies(checker ${check_profile_target})

if (NOT TARGET unchecker)
    add_custom_target(unchecker)
endif()
add_dependencies(unchecker ${clang_tidy_cancel_target})
add_dependencies(unchecker ${check_memory_cancel_target})
add_dependencies(unchecker ${check_profile_cancel_target})
